language: node_js
node_js:
- node
deploy:
  api_key:
    secure: kLu52ekZxZkGkc3oi+RfmSHQvIvRvGi4Mi9anUrom4/HlWBO/B1K2z+qeAEZKt4ObolnV0zz7ElT4JXFJ+fejF4tmX2YfPOcBRmQwmvIx/kKeEgTanxKe38/ZmOvekdXpTsP0vBsV7EK6UYsUz2RsCgLl8DF2AqrHa+KpY0TFlcSYC+nzcrPzLf0ofS21Gq9rwrpG72wJXDyGlijrzF+nBj0Si/PjD4Lm4rqkhRb9ziriqNAkI59ozMuu/x1DlzK4yWgm2XMHn3SDIfnA86NcIlS7O8/ZuAWD/G8zekZF8aQxJoxRbX7yQUolswbfpb5O0/YUugW0gjZqR/1ZIOtgr99Zdqp46FsvDXCYgoH6BmsgMhs9jCFtKj6U9icFQjwa2LDl7HU/Drc1MbC8sgQIdhP5kgExAbEb5sp4VB+ni05BQPdyGBayf357ZHCDUL6oEUeA58kAV1B3UAChJAIXJFWtC/Qh+kZiz5/drT7+OT99jyOOLe8BLMlZMI1cI5HMU3TnwmZP+lTUtdDjmDt+sQzAVrSeLsTWc6knlpmvtkvoFKO5wNqus7P5JFmcm9X6jbguRQ4/mtD5i6kbhpYcEaRTZ3+Fi/4hgEd1EzrUiwZyhiubfe1iP3Zdl7Mi7DkV+H9UIZ/hfLWs/2VdwToTNqT0ZrTPbaMn+sz6PRLCaQ=
